### ISSUE TITLE
Non standard ports

### ISSUE THREAD

**Issue by stsier** [adblockradio/webradio-metadata#1]
Did you test your module with non standard ports over https? Browsers do not allow access to many shoutcast and icecast radios that broadcast on ports different from 80 and 443. You can listen to them (and you will see warnings in the console) but you can't do other requests (errors in the console).

**Comment by dest4** [comment]
No, I did not.
Note that this module fetches metadata from websites (JSON / XML / HTTP scraping), not from audio broadcasts (ICY metadata).

**Comment by stsier** [comment]
ok so the radio has to have a website separate from the stream?

**Comment by dest4** [comment]
Yes it has. In my experience, most if not all radios have a website, while ICY metadata is most often broken.

**Comment by dest4** [comment]
Could you please give the names of those jazz webradios that do not have a website, but valid ICY metadata?

You may submit a PR that adds support for stream scraping if you think it is useful.

**Comment by stsier** [comment]
ok i double checked and actually most of them do have a website 
then I looked through your code, so you write a fetch script per radio channel to scrap the metadata? 
I have more than 60 only 30s and 40s- jazz radios.. hmm writting a script per channel is a lot of work..
for now i just scrap another big site with thousands of radios so I have the same script for any radio channel. I don't know how this website gets the metadata.

**Comment by dest4** [comment]
1) You can use the same scraping script for many radios. Just require the same scraper in `.../.../index.js`.

2) The radio aggregators have deals with radios and exchange metadata over a private API. I'd like this project to only depend on info from first parties, i.e. radio websites.

**Comment by stsier** [comment]
1. There's "parsers" directory in your repo with a script per radio. If I need a radio that is not in your list, I will have to write my own parser, right? 
2. thanks for explanation

**Comment by dest4** [comment]
I you find that the radios you want to add are compatible with an existing parser, just require it by adding a line in `.../index.js`.
If the radios are not compatible, copy paste a current parser and adapt it. There already are parsers for JSON, XML, HTTP scraping… Don't reinvent the wheel. Then add the line in `.../index.js`

**Comment by stsier** [comment]
ok thanks a lot, i will try your scripts, because scrapping a thirdparty website in the middle is not very clean
